services:
  # A series of peers.
  # As we are using Docker, we can address other containers with just their service name rather than using plain IP addresses
  peer1:
    image: chord.azurecr.io/app/dht:local_james
    build: .
    command: -address peer1 -port 8080
    expose:
      - "8080"
      - "8081"

  peer2:
    image: chord.azurecr.io/app/dht:local_james
    build: .
    command: -address peer2 -bootstrap peer1:8080 -port 8080
    expose:
      - "8080"
      - "8081"
    depends_on:
      - peer1

  peer3:
    image: chord.azurecr.io/app/dht:local_james
    build: .
    command: -address peer3 -bootstrap peer2:8080 -port 8080
    expose:
      - "8080"
      - "8081"
    depends_on:
      - peer2
        
  peer4:
    image: chord.azurecr.io/app/dht:local_james
    build: .
    command: -address peer4 -bootstrap peer3:8080 -port 8080
    expose:
      - "8080"
      - "8081"
    depends_on:
      - peer3
        
  peer5:
    image: chord.azurecr.io/app/dht:local_james
    build: .
    command: -address peer5 -bootstrap peer4:8080 -port 8080
    expose:
      - "8080"
      - "8081"
    depends_on:
      - peer4
        
  peer6:
    image: chord.azurecr.io/app/dht:local_james
    build: .
    command: -address peer6 -bootstrap peer5:8080 -port 8080
    expose:
      - "8080"
      - "8081"
    depends_on:
      - peer5
        
  # Test container which mounts our Python scripts, allows us to make use of Docker networking
  python:
    image: chord.azure.cr.io/app/python:local_james
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: python_library/Dockerfile
    volumes:
      - ./python_library:/opt/app