services:
  bootstrap:
    image: chord.azurecr.io/app/peer:ci
    network_mode: host
    command: -address 127.0.0.1 -port 8080
      
  peer:
    image: chord.azurecr.io/app/peer:ci
    deploy:
      mode: replicated
      replicas: 25
    network_mode: host
    command: -bootstrap 127.0.0.1:8080
    depends_on:
      - bootstrap