apiVersion: apps/v1
kind: Deployment
metadata:
  name: chord-peer
spec:
  replicas: 200
  selector:
    matchLabels:
      app: chord-peer
  template:
    metadata:
      labels:
        app: chord-peer
    spec:
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      imagePullSecrets:
      - name: regcred
      containers:
      - name: chord
        image: chord.azurecr.io/app/peer:ci
        command: ["/app", "-port=8080", "-address=$(EXTERNAL_IP)", "-bootstrap=10.244.3.44:8080"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "128m"
          limits:
            memory: "512Mi"
            cpu: "256m"
        ports:
        - containerPort: 8080
        env:
        - name: EXTERNAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
