# Adapted from a sample GitHub Actions Workflow
#
name: Build and Push to ACR

on:
  push:
    branches: ['main']

permissions:
  contents: read

env:
  LOGIN_SERVER: 'chord.azurecr.io'
  REGISTRY: 'chord.azurecr.io'
  NAMESPACE: 'app'
  IMAGE: 'peer'
  TAG: 'ci'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Compose Customized Docker Image'
      shell: bash
      run: |
        docker build . -t ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}:${{ env.TAG }}
        docker push ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}:${{ env.TAG }}
